services:
  server-prod:
    build:
      target: prod
      dockerfile: Dockerfile
      context: .
    volumes:
      - server-prod:/app
    ports:
      - "1234:1234"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
volumes:
  server-prod: